Fixing tsc error TS1252 in platform.ts (#801)
* Fixing tsc error TS1252 in platform.ts.

Moved the getValue function within getCurrentPlatform function outside
of function scope. Added string array parameter to getValue function
because lines was originally a local variable within the getCurrentPlatform function.

* Changing getValue function to be Map

etc/os-release is a file that has multiple 'key=value' lines.
Removing the getValue function and then have the text in
os-release to be converted to a map instead does the same thing.

* Fixing code review issues

Moving key variable into if statement.