Adding OptionsSchema for generating package.json options (#983)
* Fixing tsc error TS1252 in platform.ts.

Moved the getValue function within getCurrentPlatform function outside of function scope. Added string array
parameter to getValue function because lines was originally a local variable within the getCurrentPlatform
function.

* Adding feature for Remote .NET Attach

package.json adds listRemoteProcesses as a command, including debuggerPath into pipeTransport. The
command is registered into commands.ts. processPicker.ts has its process listing parser refactored
and now includes calling process listing to remote processes. Only works on Linux and OSX. Windows
remote attach will result in a rejected promise.

* Putting back accidentally deleted lines

* Matching style

* Reverting platform.ts and fixing code review issues

* Updating processPicker RemoteAttach to chain pipe commands

* Fixing code review issues

Added checking for platformSpecificPipeTransportOptions and added more
error checks. Required debuggerPath for attach.pipeTransport.

* Fixed code review issues: errors & formatting

Instead of creating Promise objects, used Promise.reject.
Used template strings properly and formatting.

* More code review fixes.

Adding output channel for pipe transport errors.
Fixing error messages and escaping pipe transport commands.

* More code review fixes, again.

Fixing error handling on exec calls, and clearing channel on
remoteProcessPicker startup.

* Adding packageJsonSchema

This is a valid json-schema file that will be used with the protocol
generator to get strongly typed Launch/Attach options and another script
to generate package.json.

* Adding in OptionsSchema and gulp task

OptionsSchema defines a strict type to Attach/Launch options. The gulp
task is required to be called if there are any changes to
OptionsSchema.json.

* Fixing CR issues and fixing build

* File uses capital O instead of lowercase o.

* Fixing CR issues