Fixing tsc error TS1252 in platform.ts.
Moved the getValue function within getCurrentPlatform function outside of function scope. Added string array
parameter to getValue function because lines was originally a local variable within the getCurrentPlatform
function.